"""Differentiable tag rendering and camera response model (JAX)."""

from render_model.camera import (
    CameraPipeline,
    GammaCamera,
    GaussianNoiseCamera,
    LinearCamera,
    SharpeningCamera,
)
from render_model.display import (
    IMSHOW_KWARGS,
    PIXELATED_STYLE,
    configure_matplotlib_image_display,
    centered_diff_limits,
    imshow_extent,
    pixelated_grid,
    pixelated_image,
)
from render_model.esf import ESFProfile, estimate_esf_from_target, esf_profile_from_samples
from render_model.esf_optimizer import ESFConfig, OptimizeConfig, optimize_homography
from render_model.gamma import apply_gamma
from render_model.homography import (
    apply_homography,
    corner_rmse,
    corner_reprojection_loss,
    corners_from_homography,
    corners_from_normal_offsets,
    corners_from_uniform_normal_offset,
    edge_normal_distances,
    edge_outward_normals,
    homography_from_corners,
    homography_to_params,
    numpy_corners_from_normal_offsets,
    numpy_corners_from_uniform_normal_offset,
    numpy_dlt_homography,
    numpy_sample_normal_offset_corners,
    numpy_sample_uniform_normal_offset_corners,
    params_to_homography,
)
from render_model.camera_params import (
    camera_params_physical_vector,
    decode_joint_params_per_step,
)
from render_model.optimizer import (
    DEFAULT_HOMOGRAPHY_PARAM_LR_SCALES,
    JOINT_PARAM_NAMES,
    OptimizationParamTrace,
    OptimizationTrace,
    OptimizeLMConfig,
    OptimizeRenderConfig,
    apply_psf_continuation_to_camera,
    first_step_corner_rmse_below,
    homography_param_lr_scales,
    model_params_to_vector,
    optimize_render_model,
    optimize_render_model_lm,
    optimize_render_model_lm_with_param_trace,
    optimize_render_model_with_param_trace,
    optimize_render_model_with_trace,
    vector_to_model_params,
)
from render_model.pipeline import (
    SUPERSAMPLE,
    RenderModelParams,
    RenderModelStages,
    apply_render_model,
    bin_down,
    default_params,
    render_with_model,
    render_with_model_stages,
    scale_homography,
)
from render_model.psf import KERNEL_RADIUS, apply_gaussian_psf, gaussian_kernel_1d
from render_model.renderer import (
    bbox_mask,
    quad_mask,
    filtered_squares,
    render_tag,
    render_tag_antialiased,
    render_tag_esf,
    render_tag_esf_supersampled,
    render_tag_filtered,
    render_tag_supersampled,
)
from render_model.scene import RenderScene, TagGrid, TagInstance
from render_model.sharpen import apply_sharpening
from render_model.tag_data import TAG_CANONICAL_CORNERS, TAG_GRID_SIZE, build_tag_pattern

__all__ = [
    "IMSHOW_KWARGS",
    "KERNEL_RADIUS",
    "PIXELATED_STYLE",
    "SUPERSAMPLE",
    "TAG_CANONICAL_CORNERS",
    "TAG_GRID_SIZE",
    "CameraPipeline",
    "ESFConfig",
    "ESFProfile",
    "GammaCamera",
    "GaussianNoiseCamera",
    "LinearCamera",
    "OptimizationTrace",
    "OptimizeConfig",
    "DEFAULT_HOMOGRAPHY_PARAM_LR_SCALES",
    "JOINT_PARAM_NAMES",
    "OptimizationParamTrace",
    "OptimizeLMConfig",
    "OptimizeRenderConfig",
    "RenderModelParams",
    "RenderModelStages",
    "RenderScene",
    "SharpeningCamera",
    "TagGrid",
    "TagInstance",
    "apply_gamma",
    "apply_gaussian_psf",
    "apply_homography",
    "apply_psf_continuation_to_camera",
    "apply_render_model",
    "apply_sharpening",
    "bbox_mask",
    "quad_mask",
    "bin_down",
    "build_tag_pattern",
    "camera_params_physical_vector",
    "decode_joint_params_per_step",
    "centered_diff_limits",
    "configure_matplotlib_image_display",
    "corner_reprojection_loss",
    "corner_rmse",
    "corners_from_homography",
    "corners_from_normal_offsets",
    "corners_from_uniform_normal_offset",
    "edge_normal_distances",
    "edge_outward_normals",
    "default_params",
    "estimate_esf_from_target",
    "esf_profile_from_samples",
    "filtered_squares",
    "first_step_corner_rmse_below",
    "homography_param_lr_scales",
    "gaussian_kernel_1d",
    "homography_from_corners",
    "homography_to_params",
    "imshow_extent",
    "model_params_to_vector",
    "numpy_corners_from_normal_offsets",
    "numpy_corners_from_uniform_normal_offset",
    "numpy_dlt_homography",
    "numpy_sample_normal_offset_corners",
    "numpy_sample_uniform_normal_offset_corners",
    "optimize_homography",
    "optimize_render_model",
    "optimize_render_model_lm",
    "optimize_render_model_lm_with_param_trace",
    "optimize_render_model_with_param_trace",
    "optimize_render_model_with_trace",
    "params_to_homography",
    "pixelated_grid",
    "pixelated_image",
    "render_tag",
    "render_tag_antialiased",
    "render_tag_esf",
    "render_tag_esf_supersampled",
    "render_tag_filtered",
    "render_tag_supersampled",
    "render_with_model",
    "render_with_model_stages",
    "scale_homography",
    "vector_to_model_params",
]
